

#ifndef STM32H7XX_STRHAL_INC_STRHAL_CAN_CONFIG_H_
#define STM32H7XX_STRHAL_INC_STRHAL_CAN_CONFIG_H_

#ifndef INC_CAN_CONFIG_H_
#define INC_CAN_CONFIG_H_

#define FDCAN_TIMEOUT_VALUE					1000

#define FDCAN_ELMTS_ARRAY_SIZE				64
#define FDCAN_ELMTS_SIZE					FDCAN_DATA_BYTES_64

#define FDCAN_NOMINAL_PRESCALER				8
#define FDCAN_NOMINAL_SYNC_JUMP_WIDTH		1
#define FDCAN_NOMINAL_TIMESEG_1				7
#define FDCAN_NOMINAL_TIMESEG_2				2

#define FDCAN_DATA_PRESCALER				1
#define FDCAN_DATA_SYNC_JUMP_WIDTH			1
#define FDCAN_DATA_TIMESEG_1				7
#define FDCAN_DATA_TIMESEG_2				2

#define FDCAN_STD_FILTER_NUMBER				4
#define FDCAN_EXT_FILTER_NUMBER				0
#define FDCAN_RX_FIFO0_ELMTS_NUMBER			4
#define FDCAN_RX_FIFO0_ELMTS_SIZE			FDCAN_ELMTS_SIZE
#define FDCAN_RX_FIFO1_ELMTS_NUMBER			4
#define FDCAN_RX_FIFO1_ELMTS_SIZE			FDCAN_ELMTS_SIZE
#define FDCAN_RX_BUFFER_NUMBER				0
#define FDCAN_RX_BUFFER_SIZE				FDCAN_ELMTS_SIZE
#define FDCAN_TX_EVENT_NUMBER				0
#define FDCAN_TX_BUFFER_NUMBER				0
#define FDCAN_TX_FIFO_QUEUE_ELMTS_NUMBER	10
#define FDCAN_TX_FIFO_QUEUE_MODE			FDCAN_TX_FIFO_OPERATION //FDCAN_TX_QUEUE_OPERATION
#define FDCAN_TX_ELMTS_SIZE					FDCAN_ELMTS_SIZE

#define FDCAN_TDC_OFFSET					5
#define FDCAN_TDC_FILTER					0

#endif

#endif /* STM32H7XX_STRHAL_INC_STRHAL_CAN_CONFIG_H_ */
