#ifndef INC_CAN_CONFIG_H_
#define INC_CAN_CONFIG_H_


#define CAN_TIMEOUT_VALUE				1000

#define CAN_ELMTS_ARRAY_SIZE			64
#define CAN_ELMTS_SIZE					FDCAN_DATA_BYTES_64

#define CAN_NOMINAL_PRESCALER			4
#define CAN_NOMINAL_SYNC_JUMP_WIDTH		2
#define CAN_NOMINAL_TIMESEG_1			12
#define CAN_NOMINAL_TIMESEG_2			5
#define CAN_DATA_PRESCALER				1
#define CAN_DATA_SYNC_JUMP_WIDTH		2
#define CAN_DATA_TIMESEG_1				12
#define CAN_DATA_TIMESEG_2				5
#define CAN_STD_FILTER_NUMBER			4
#define CAN_EXT_FILTER_NUMBER			1
#define CAN_RX_FIFO0_ELMTS_NUMBER		4
#define CAN_RX_FIFO0_ELMTS_SIZE			CAN_ELMTS_SIZE
#define CAN_RX_FIFO1_ELMTS_NUMBER		4
#define CAN_RX_FIFO1_ELMTS_SIZE			CAN_ELMTS_SIZE
#define CAN_RX_BUFFER_NUMBER			1
#define CAN_RX_BUFFER_SIZE				CAN_ELMTS_SIZE
#define CAN_TX_EVENT_NUMBER				1
#define CAN_TX_BUFFER_NUMBER			1
#define CAN_TX_FIFO_QUEUE_ELMTS_NUMBER	4
#define CAN_TX_FIFO_QUEUE_MODE			FDCAN_TX_QUEUE_OPERATION
#define CAN_TX_ELMTS_SIZE				CAN_ELMTS_SIZE

#define CAN_TDC_OFFSET					12
#define CAN_TDC_FILTER					0



#endif
