#ifndef LID_ADC_H
#define LID_ADC_H

#include <stm32g4xx.h>
#include <stm32g4xx_ll_adc.h>
#include <stm32g4xx_ll_bus.h>
#include <stm32g4xx_ll_gpio.h>
#include <stm32g4xx_ll_dma.h>
#include <stm32g4xx_ll_dmamux.h>
#include <stm32g4xx_ll_rcc.h>

/***** DEFINES *****/
//ADC
//#define LID_ADC_N_CHANNELS 19
#define LID_ADC_CHANNEL_SAMPLINGTIME LL_ADC_SAMPLINGTIME_12CYCLES_5
#define LID_ADC_SINGLEDIFF LL_ADC_SINGLE_ENDED
#define LID_ADC_RESOLUTION LL_ADC_RESOLUTION_12B
#define LID_ADC_COMMONCLOCK LL_ADC_CLOCK_SYNC_PCLK_DIV2
//DMA
#define LID_ADC_DMA DMA1
#define LID_ADC_DMA_CHANNEL LL_DMA_CHANNEL_3 // the 3 DMA channels start here
#define LID_ADC_DMA_PRIORITY LL_DMA_PRIORITY_HIGH

typedef enum {
	LID_ADC_TYPE_SINGLE,
	LID_ADC_TYPE_CONT
} LID_ADC_Channel_Type_t;

typedef enum {
	LID_ADC_CHANNEL_0 = 0,
	LID_ADC_CHANNEL_1,
	LID_ADC_CHANNEL_2,
	LID_ADC_CHANNEL_3,
	LID_ADC_CHANNEL_4,
	LID_ADC_CHANNEL_5,
	LID_ADC_CHANNEL_6,
	LID_ADC_CHANNEL_7,
	LID_ADC_CHANNEL_8,
	LID_ADC_CHANNEL_9,
	LID_ADC_CHANNEL_10,
	LID_ADC_CHANNEL_11,
	LID_ADC_CHANNEL_12,
	LID_ADC_CHANNEL_13,
	LID_ADC_CHANNEL_14,
	LID_ADC_CHANNEL_15,
	LID_ADC_CHANNEL_16,
	LID_ADC_CHANNEL_17,
	LID_ADC_CHANNEL_18,

	LID_ADC_CHANNEL_LAST
} LID_ADC_ChannelId_t;

typedef enum {
	LID_ADC_INTYPE_REGULAR,
	LID_ADC_INTYPE_OPAMP
} LID_ADC_InType_t;

typedef struct {
	GPIO_TypeDef * port;
	uint32_t pin;
	LID_ADC_InType_t type;
	uint32_t channel;
} LID_ADC_AnalogPin_t;

typedef struct {
	ADC_TypeDef *ADCx;
	LID_ADC_ChannelId_t channelId;
} LID_ADC_Channel_t;

typedef volatile uint16_t LID_ADC_Data_t;

void LID_ADC_Init();

LID_ADC_Data_t * LID_ADC_SubscribeChannel(LID_ADC_Channel_t *channel, LID_ADC_InType_t type);

void LID_ADC_Run();

/*
PRESS_0 PB15 ADC2_IN15 ADC2
PRESS_1 PB13 ADC3_IN5 ADC3
PRESS_2 PB11 ADC12_IN14 ADC1
PRESS_3 PD10 ADC3_IN7 ADC3
PRESS_4 PB14 ADC1_IN5 ADC1
PRESS_5 PB12 ADC1_IN11 ADC1

TEMP_0 PC0 ADC12_IN6 ADC1
TEMP_1 PC1 ADC12_IN7 ADC1
TEMP_2 PC2 ADC12_IN8 ADC1

SERVO_0_CURR PA0 ADC12_IN1 ADC1
SERVO_1_CURR PA2 ADC1_IN3 ADC1
SERVO_2_CURR PA4 ADC2_IN17 ADC2

SERVO_0_FDBK PC3 ADC1_IN9 ADC1
SERVO_1_FDBK PA1 ADC1_IN2 ADC1
SERVO_2_FDBK PA3 ADC1_IN4 ADC1

SOLENOID_0_CURR OPAMP PA7 OPAMP2_VINP ADC2_IN16 ADC2
SOLENOID_1_CURR OPAMP PB0 OPAMP3_VINP ADC2_IN18 ADC2

PYRO_0_CURR PE9 ADC3_IN2 ADC3
PYRO_1_CURR PE8 ADC3_IN6 ADC3
PYRO_2_CURR PE7 ADC3_IN4 ADC3

12V_SENSE PA6 ADC2_IN3 ADC2
12VA_SENSE PC5 ADC2_IN11 ADC2
5V_SENSE PC4 ADC2_IN5 ADC2
PYRO_SENSE PB1 ADC1_IN12 ADC1
*/

/*typedef enum {
	LID_ADC_PRESS_0,
	LID_ADC_PRESS_1,
	LID_ADC_PRESS_2,
	LID_ADC_PRESS_3,
	LID_ADC_PRESS_4,
	LID_ADC_PRESS_5,
	LID_ADC_TEMP_0,
	LID_ADC_TEMP_1,
	LID_ADC_TEMP_2,
	LID_ADC_SERVO_0_CURR,
	LID_ADC_SERVO_1_CURR,
	LID_ADC_SERVO_2_CURR,
	LID_ADC_SERVO_0_FDBK,
	LID_ADC_SERVO_1_FDBK,
	LID_ADC_SERVO_2_FDBK,
	LID_ADC_SOLENOID_0_CURR,
	LID_ADC_SOLENOID_1_CURR,
	LID_ADC_PYRO_0_CURR,
	LID_ADC_PYRO_1_CURR,
	LID_ADC_PYRO_2_CURR,
	LID_ADC_12V_SENSE,
	LID_ADC_12VA_SENSE,
	LID_ADC_5V_SENSE,
	LID_ADC_PYRO_SENSE,

	LID_ADC_CHANNEL_LAST
} LID_ADC_Channel_Id_t;*/

/*{
[LID_ADC_SERVO_0_CURR] =	{ ADC1, LL_ADC_CHANNEL_1 },
[LID_ADC_SERVO_1_FDBK] =	{ ADC1, LL_ADC_CHANNEL_2 },
[LID_ADC_SERVO_1_CURR] =	{ ADC1, LL_ADC_CHANNEL_3 },
[LID_ADC_SERVO_2_FDBK] =	{ ADC1, LL_ADC_CHANNEL_4 },
[LID_ADC_PRESS_4] =			{ ADC1, LL_ADC_CHANNEL_5 },
[LID_ADC_TEMP_0] =			{ ADC1, LL_ADC_CHANNEL_6 },
[LID_ADC_TEMP_1] =			{ ADC1, LL_ADC_CHANNEL_7 },
[LID_ADC_TEMP_2] =			{ ADC1, LL_ADC_CHANNEL_8 },
[LID_ADC_SERVO_0_FDBK] =	{ ADC1, LL_ADC_CHANNEL_9 },
[LID_ADC_PRESS_5] =			{ ADC1, LL_ADC_CHANNEL_11 },
[LID_ADC_PYRO_SENSE] =		{ ADC1, LL_ADC_CHANNEL_12 }
[LID_ADC_PRESS_2] =			{ ADC1, LL_ADC_CHANNEL_14 },

[LID_ADC_12V_SENSE] =		{ ADC2, LL_ADC_CHANNEL_3 },
[LID_ADC_5V_SENSE] =		{ ADC2, LL_ADC_CHANNEL_5 },
[LID_ADC_12VA_SENSE] =		{ ADC2, LL_ADC_CHANNEL_11 },
[LID_ADC_PRESS_0] =			{ ADC2, LL_ADC_CHANNEL_15 },
[LID_ADC_SERVO_2_CURR] =	{ ADC2, LL_ADC_CHANNEL_17 },
[LID_ADC_SOLENOID_0_CURR] =	{ ADC2, LL_ADC_CHANNEL_VOPAMP2 },
[LID_ADC_SOLENOID_1_CURR] =	{ ADC2, LL_ADC_CHANNEL_VOPAMP3_ADC2 },

[LID_ADC_PYRO_0_CURR] =		{ ADC3, LL_ADC_CHANNEL_2 },
[LID_ADC_PYRO_2_CURR] =		{ ADC3, LL_ADC_CHANNEL_4 },
[LID_ADC_PRESS_1] =			{ ADC3, LL_ADC_CHANNEL_5 },
[LID_ADC_PYRO_1_CURR] =		{ ADC3, LL_ADC_CHANNEL_6 },
[LID_ADC_PRESS_3] =			{ ADC3, LL_ADC_CHANNEL_7 },
};*/

#endif
